### Fixing userDAO.py
userDAO.py
```python
# Validates a user login. Returns user record or None
def validate_login(self, username, password):

    user = None
    try:
        user = self.users.find_one({'_id':username})
        .
        .
        .

# creates a new user in the users collection
  def add_user(self, username, password, email):
      password_hash = self.make_pw_hash(password)

      user = {'_id': username, 'password': password_hash}
      if email != "":
          user['email'] = email

      try:
          self.users.insert_one(user)
          .
          .
          .  
```

Validation code:
jkfds5834j98fnm39njf0920f02
